HEVS_S8_GIS_Camping/CampMAP/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # **** Manage users ****
    path('signup/', views.signup_user, name='signup'),
    path('reserve/', views.reserve_slot, name='reserve'),
    path('', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    # **** App urls ****
    path('homepage/', views.homepage, name='homepage'),
    path('homepage/reserve/<int:id_place>', views.reserve_slot, name='reserve'),
    path('accept/', views.update_reservation, name='accept'),
    path('decline/', views.delete_reservation, name='decline'),
    # **** Json files ****
    path('places.json/', views.placesjson, name='placesjson'),
    path('oneplace.json/<int:id_place>', views.oneplacejson, name='oneplacejson'),
    path('reservedplaces.json/', views.reservedplacesjson, name='reservedplacesjson'),
    path('bookedplaces.json/', views.bookedplacesjson, name='bookedplacesjson'),
    path('buildings.json/', views.buildingsjson, name='buildingsjson'),
    path('campingareas.json/', views.campingareasjson, name='campingareasjson'),
    path('pools.json/', views.poolsjson, name='poolsjson'),
    path('trees.json/', views.treesjson, name='treesjson'),
    path('userbookings.json/', views.userbookingjson, name='userbookingjson'),

    path(
        'applyfilters.json/<int:pool_max_range>/<int:max_neighbour>/<str:tree_option>/<int:pet_min_range>/<int:children_min_range>/',
        views.applyfilters, name='applyfiltersjson'
    )
]

HEVS_S8_GIS_Camping/HEVS_S8_GIS_Camping/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('CampMAP.urls')),
    path('admin/', admin.site.urls)
]

HEVS_S8_GIS_Camping/CampMAP/models.py
from django.contrib.gis.db import models
from django.contrib.auth.models import User


# **** Model for the authentication part ****
class Camper(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    adults = models.PositiveIntegerField()
    kids = models.PositiveIntegerField()
    pets = models.BooleanField()


# **** All models from the database ****
class Place(models.Model):
    gid = models.PositiveIntegerField(primary_key=True)
    geom = models.MultiPolygonField(srid=4326, null=True)

    class Meta:
        db_table = "places"

    def __int__(self):
        return self.gid


class Building(models.Model):
    gid = models.PositiveIntegerField(primary_key=True)
    geom = models.MultiPolygonField(srid=4326, null=True)

    class Meta:
        db_table = "buildings"

    def __int__(self):
        return self.gid


class CampingArea(models.Model):
    gid = models.PositiveIntegerField(primary_key=True)
    geom = models.MultiPolygonField(srid=4326, null=True)

    class Meta:
        db_table = "camping_areas"

    def __int__(self):
        return self.gid


class Pool(models.Model):
    gid = models.PositiveIntegerField(primary_key=True)
    geom = models.MultiPolygonField(srid=4326, null=True)

    class Meta:
        db_table = "pools"

    def __int__(self):
        return self.gid


class Tree(models.Model):
    gid = models.PositiveIntegerField(primary_key=True)
    geom = models.PointField(srid=4326, null=True)

    class Meta:
        db_table = "trees"

    def __int__(self):
        return self.gid


# **** Relational table ****
class Reservation(models.Model):
    camper = models.ForeignKey('Camper', related_name='camper_id', on_delete=models.DO_NOTHING)
    place = models.ForeignKey('Place', related_name='place_id', on_delete=models.DO_NOTHING)
    status = models.PositiveIntegerField()

HEVS_S8_GIS_Camping/CampMAP/views.py
from django.shortcuts import render, redirect
from django.core.serializers import serialize
from django.http import HttpResponse
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from .classes.RegisterForm import RegisterForm
from .classes.CampDistances import CampDistances
from .models import *


# **** Manage users views below ****
def signup_user(request):
    if request.user.is_authenticated:
        return redirect('homepage')
    else:
        if request.method == 'POST':
            form = RegisterForm(request.POST)
            if form.is_valid():
                # create user
                user = form.save()
                # create camper
                adults = form.cleaned_data.get('adults')
                if not adults:
                    adults = 0
                kids = form.cleaned_data.get('kids')
                if not kids:
                    kids = 0
                pets = form.cleaned_data.get('pets')
                camper = Camper(adults=adults, kids=kids, pets=pets, user_id=user.id)
                camper.save()
                # log the user in
                login(request, user)
                return redirect('homepage')
        else:
            form = RegisterForm()
        return render(request, 'signup.html', {'form': form})


def login_user(request):
    if request.user.is_authenticated:
        return redirect('homepage')
    else:
        if request.method == 'POST':
            form = AuthenticationForm(data=request.POST)
            if form.is_valid():
                user = form.get_user()
                login(request, user)
                return redirect('homepage')
        else:
            form = AuthenticationForm()
        return render(request, 'index.html', {'form': form})


def logout_user(request):
    if request.method == 'POST':
        logout(request)
        return redirect('login')


def reserve_slot(request, id_place):
    if request.user.is_superuser:
        return HttpResponse('Admins can only approved reservations, not reserve.')
    camper = Camper.objects.get(user_id=request.user.id)
    place = Place.objects.get(gid=id_place)
    existingReservation = Reservation.objects.filter(camper=camper, place=place)
    if len(existingReservation) > 0:
        return HttpResponse('<script>window.history.back();</script>')
    else:
        reservation = Reservation(camper=camper, place=place, status=1)
        reservation.save()
        return redirect('homepage')


# **** App views below ****
@login_required(login_url='/')
def homepage(request):
    # retrieve reservations
    reservations = Reservation.objects.filter(status=1)
    booked = Reservation.objects.filter(status=2)
    return render(request, 'homePage.html', {'reservations': reservations, 'booked': booked})


def delete_reservation(request):
    id = request.POST.get('decline')
    Reservation.objects.filter(id=id).delete()
    return redirect('homepage')


def update_reservation(request):
    id = request.POST.get('accept')
    Reservation.objects.filter(id=id).update(status=2)
    Reservation.objects.filter(place = Reservation.objects.get(id=id).place, status = 1).delete()
    return redirect('homepage')


# **** Json views below ****
def placesjson(request):
    bookings = Reservation.objects.filter(status=2)
    unavailable_ids = []
    for booking in bookings:
        unavailable_ids.append(booking.place_id)
    places = Place.objects.all().exclude(gid__in=unavailable_ids)
    ser = serialize('geojson', places, geometry_field='geom')
    return HttpResponse(ser)

def oneplacejson(request,id_place):
    place = Place.objects.filter(gid = id_place)
    print('oi')
    print(place)
    ser = serialize('geojson', place, geometry_field='geom')
    return HttpResponse(ser)

def buildingsjson(request):
    buildings = Building.objects.all()
    ser = serialize('geojson', buildings, geometry_field='geom')
    return HttpResponse(ser)


def campingareasjson(request):
    camping_areas = CampingArea.objects.all()
    ser = serialize('geojson', camping_areas, geometry_field='geom')
    return HttpResponse(ser)


def poolsjson(request):
    pools = Pool.objects.all()
    ser = serialize('geojson', pools, geometry_field='geom')
    return HttpResponse(ser)


def applyfilters(request, pool_max_range, max_neighbour, tree_option, pet_min_range, children_min_range):
    trees = Tree.objects.all()
    pools = Pool.objects.all()
    places = Place.objects.all()
    bookings = Reservation.objects.filter(status=2)

    # 1 - filter by pool range
    filtered_places = CampDistances.get_shapes_in_range_from(places, pools, 0, pool_max_range)

    # 2 - filter with tree
    places_filtered_with_tree = CampDistances.get_shapes_into_other_shapes(filtered_places, trees)

    if tree_option == "with":
        filtered_places = places_filtered_with_tree
    elif tree_option == "without":
        for place_with_tree in places_filtered_with_tree:
            if place_with_tree in filtered_places:
                filtered_places.remove(place_with_tree)

    # 3 - filter  neighbour
    places_within_max_neighbour = []
    for place in filtered_places:
        intersect_shapes = CampDistances.get_shapes_intersects_other_shape(place, places)
        if len(intersect_shapes) <= max_neighbour:
            places_within_max_neighbour.append(place)
    filtered_places = places_within_max_neighbour

    # 4 - filter pets and kids
    # 4A - Get places with pets and kids
    places_with_pets = []
    places_with_kids = []
    for booking in bookings:
        if booking.camper.pets is True:
            places_with_pets.append(booking.place)
        if booking.camper.kids > 0:
            places_with_kids.append(booking.place)

    # 4B  - filter pet
    places_away_from_pets = []
    for place in filtered_places:
        distance_from_pets = CampDistances.get_min_distance_from_objects(places_with_pets, place)
        if distance_from_pets >= pet_min_range:
            places_away_from_pets.append(place)
    filtered_places = places_away_from_pets

    # 4C  - filter kids
    places_away_from_kids = []
    for place in filtered_places:
        distance_from_kids = CampDistances.get_min_distance_from_objects(places_with_kids, place)
        if distance_from_kids >= children_min_range:
            places_away_from_kids.append(place)
    filtered_places = places_away_from_kids

    # 5 - removed booked places
    for booking in bookings:
        if booking.place in filtered_places:
            filtered_places.remove(booking.place)

    ser = serialize('geojson', filtered_places, geometry_field='geom')
    return HttpResponse(ser)


def treesjson(request):
    trees = Tree.objects.all()
    ser = serialize('geojson', trees, geometry_field='geom')
    return HttpResponse(ser)


def reservedplacesjson(request):
    reservations = Reservation.objects.filter(status=1)
    unavailable_ids = []
    for res in reservations:
        unavailable_ids.append(res.place_id)
    places = Place.objects.filter(gid__in=unavailable_ids)
    ser = serialize('geojson', places, geometry_field='geom')
    return HttpResponse(ser)


def bookedplacesjson(request):
    bookings = Reservation.objects.filter(status=2)
    unavailable_ids = []
    for booking in bookings:
        unavailable_ids.append(booking.place_id)
    places = Place.objects.filter(gid__in=unavailable_ids)
    ser = serialize('geojson', places, geometry_field='geom')
    return HttpResponse(ser)


def userbookingjson(request):
    if(request.user.is_superuser) :
        return HttpResponse([])
    camper = Camper.objects.get(user_id=request.user.id)
    print(camper)
    bookings = Reservation.objects.filter(status=2, camper=camper) | Reservation.objects.filter(status=1, camper=camper)
    user_places = []
    for booking in bookings:
        place = Place.objects.get(gid=booking.place_id)
        user_places.append(place)
    ser = serialize('geojson', user_places, geometry_field='geom')
    return HttpResponse(ser)

HEVS_S8_GIS_Camping/CampMAP/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>

        <!-- **** Bootstrap library **** -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

        <!-- **** Customized styles **** -->
        <link rel="stylesheet" type="text/css" href="{% static "style.css" %}">
    </head>
    <body>
        {% block contents %}
        {% endblock %}
    </body>
</html>

HEVS_S8_GIS_Camping/CampMAP/templates/homePage.html
{% load leaflet_tags %}
{% load static %}

<head>
    <!-- **** Bootstrap library **** -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          crossorigin="anonymous">
    <!-- **** Customized styles **** -->
    <link rel="stylesheet" type="text/css" href="{% static "style.css" %}">
    <script src="https://kit.fontawesome.com/67065feb7d.js" crossorigin="anonymous"></script>
    <title>Camper Home Page</title>

    <!-- **** Add the leaflet components **** -->
    {% leaflet_js %}
    {% leaflet_css %}

    <!-- **** Add the javascripts (jquery and to draw the map) **** -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script type="text/javascript" src="{% static "map.js" %}"></script>
</head>
<body onload="initialize()" style="font-family: 'Times New Roman', serif;">
<!-- **** Connected as superuser **** -->
{% if user.is_superuser %}

    <!-- **** Navbar **** -->
    <nav class="navbar navbar-dark sticky-top flex-md-nowrap p-0 shadow" style="background-color: #996633; font-weight: bold;">
        <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="#">Manager Home Page</a>
        <ul class="navbar-nav px-3" id="navItems">
            <li class="nav-item text-nowrap">
                <text class="navbar-brand px-3">Welcome back, {{ user.username }}!</text>
                <text id='user-id' style="display: none"> {{ user.id }}</text>
                <form class="logout-link" action="{% url 'logout' %}" method="post" style="display: inline">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-link logout px-3"><i class="fas fa-sign-out-alt"></i></button>
                </form>
            </li>
        </ul>
    </nav>

    <div class="row">
        <div class="row-md-8"></div>
        <div class="col-md-8">
            <div class="container" style="margin-top: 45px; width: 80%; font-family: 'Times New Roman', serif;">
                <text id='user-id' style="display: none" data-user-name="{{ user.username }}"
                      data-user-id="{{ user.id }}"></text>
                <div class="warning alert-warning">
                    <h3 style="font-style: italic; margin-bottom: 25px; padding-left: 20px; background-color: #ff6d65; color: black;">
                        Hello {{ user.username }}, below you will find the current pending bookings!</h3>
                </div>
                <!-- For each reservation, create a card -->
                {% for reservation in reservations %}
                    <div class="card" style="margin-bottom: 15px;">
                        <h5 class="card-header" style="text-transform: uppercase; font-weight: bold;">Reservation for
                            the place number {{ reservation.place.gid }}</h5>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-8">
                                    <h5 class="card-title" style="font-weight: bold;">Camper informations</h5>
                                    <p class="card-text">
                                        <span>Camper name: </span>{{ reservation.camper.user.first_name }} {{ reservation.camper.user.last_name }}<br/>
                                        <span>Email address: </span>{{ reservation.camper.user.email }}<br/>
                                        <span>Number of adults: </span>{{ reservation.camper.adults }}<br/>
                                        <span>Number of kids: </span>{{ reservation.camper.kids }}<br/>
                                        <span>Does this camper have any pet? </span>{% if reservation.camper.pets %}
                                        Yes{% else %}No{% endif %}
                                    </p>
                                </div>
                                <div class="col-md-4">
                                    <form action="{% url 'accept' %}" method="post" style="display: inline">
                                        {% csrf_token %}
                                        <button type="submit" name="accept" value="{{ reservation.id }}"
                                                class="btn btn-success">Accept
                                        </button>
                                    </form>
                                    <form action="{% url 'decline' %}" method="post" style="display: inline">
                                        {% csrf_token %}
                                        <button type="submit" name="decline" value="{{ reservation.id }}"
                                                class="btn btn-danger">Decline
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4">
            <div class="container" style="margin-top: 45px; width: 80%">
                <table style="width: 100%">
                    <tr>
                        <th colspan="2">Slots already booked</th>
                    </tr>
                    {% for reservation in booked %}
                        <tr>
                            <td>Slot number {{ reservation.place.gid }}
                                : {{ reservation.camper.user.first_name }} {{ reservation.camper.user.last_name }} </td>
                            <td>

                                <form action="{% url 'decline' %}" method="post" style="display: inline">
                                    {% csrf_token %}
                                    <button type="submit" name="decline" value="{{ reservation.id }}"
                                            class="btn btn-link empty" style="float: right;">
                                        <i class="fas fa-times-circle"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
            <div class="container" style="margin-top: 45px; width: 80%; height : 300px">
                <div id="campingmap" style="width:100%; height:100%"></div>
            </div>
        </div>
    </div>

    <!-- **** Connected as standard user **** -->
{% else %}
    <!-- **** Navbar **** -->
    <nav class="navbar navbar-dark sticky-top flex-md-nowrap p-0 shadow" style="background-color: #87ba59; font-weight: bold;">
        <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="#">Camper Home Page</a>
        <ul class="navbar-nav px-3" id="navItems">
            <li class="nav-item text-nowrap">
                <text class="navbar-brand px-3">Welcome, {{ user.username }}!</text>
                <text id='user-id' style="display: none" data-user-name="{{ user.username }}"
                      data-user-id="{{ user.id }}"></text>
                <form class="logout-link" action="{% url 'logout' %}" method="post" style="display: inline">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-link logout px-3"><i class="fas fa-sign-out-alt"></i></button>
                </form>
            </li>
        </ul>
    </nav>

    <!-- **** Main content **** -->
    <div class="container-fluid m-0 p-0">
        <!-- **** Map **** -->
        <div class="col-md-10 m-0 p-0">
            <div id="campingmap" style="width:100%; height:100%"></div>
        </div>

        <!-- **** Sidebar **** -->
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse ml-0 pl-0 ">
            <div class="sidebar-sticky p-3">
                <form id="filter-form">

                    <label for="filter" style="font-weight: bold;">Filters for places that are:</label>
                    <div class="form-check">
                        <label class="form-check-label" for="pool-max-range">
                            In pools' range of: <span id="pool-max-range-value">300</span> m
                        </label>
                        <input type="range" min="30" max="300" value="300" class="slider" id="pool-max-range" autocomplete="off"
                               onchange="displayPoolRange(this.value)">
                    </div>
                    <div class="form-check">
                        <label class="form-check-label" for="max-neighbour">
                            With maximum <span id="max-neighbour-value">8</span> neighbour(s)
                        </label>
                        <input type="range" min="1" max="8" value="8" class="slider" id="max-neighbour" autocomplete="off"
                               onchange="displayMaxNeighbour(this.value)">
                    </div>
                    <div class="form-check">
                        <label class="form-check-label" for="pets-min-range">
                            At least <span id="pets-min-range-value">0</span> m away from pets
                        </label>
                        <input type="range" min="0" max="150" value="0" class="slider" id="pets-min-range" autocomplete="off"
                               onchange="displayPetRange(this.value)">
                    </div>
                    <div class="form-check">
                        <label class="form-check-label" for="children-min-range">
                            At least <span id="children-min-range-value">0</span> m away from kids
                        </label>
                        <input type="range" min="0" max="150" value="0" class="slider" id="children-min-range" autocomplete="off"
                               onchange="displayChildrenRange(this.value)">
                    </div>
                    <label class="mt-4" style="font-weight: bold;">What kind of places are you interested in?</label>
                    <div class="form-check">
                        <div class="radio" name="radio_container">
                            <label>
                                <input type="radio" name="trees-filter" value="all" checked>
                                <span class="checkmark"></span> All places
                            </label>
                        </div>
                        <div class="radio" name="radio_container">
                            <label>
                                <input type="radio" name="trees-filter" value="with">
                                <span class="checkmark"></span> Places with trees
                            </label>
                        </div>
                        <div class="radio" name="radio_container">
                            <label>
                                <input type="radio" name="trees-filter" value="without">
                                <span class="checkmark"></span> Places without trees
                            </label>
                        </div>
                    </div>
                    <button type="button" class="btn btn-success mt-2" onclick="applyAllFilters()">Apply filters
                    </button>
                </form>
            </div>
        </nav>
    </div>
{% endif %}

<!-- **** Bootstrap CDN **** -->
<script src="../assets/dist/js/bootstrap.bundle.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>

<!-- **** Personalized script **** -->
<script>

    function displayPoolRange(val) {
        $("#pool-max-range-value").html(val);
    }

    function displayMaxNeighbour(val) {
        $("#max-neighbour-value").html(val);
    }

    function displayPetRange(val) {
        $("#pets-min-range-value").html(val);
    }

    function displayChildrenRange(val) {
        $("#children-min-range-value").html(val);
    }

    function applyAllFilters() {
        applyFilters();
    }

</script>
</body>

HEVS_S8_GIS_Camping/CampMAP/templates/signup.html
{% extends "base.html" %}

<!-- **** Custom <head> contents **** -->
{% block title %}Sign up{% endblock %}

<!-- **** Page <body> proper contents **** -->
{% block contents %}
<div class="fullscreen">
    <div class="container center-div">
        <div class="container">
            <h1 style="margin-top: 15px; margin-bottom: 25px;">Register</h1>
            <form class="site-form" action="/signup/" method="post" style="font-size:11pt;">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input id="id_first_name" name="first_name" class="form-control form-control-sm" type="text" maxlength="32" placeholder="First name" required>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <input id="id_last_name" name="last_name" class="form-control form-control-sm" type="text" maxlength="32" placeholder="Last name" required>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <input id="id_email" name="email" class="form-control form-control-sm" type="email" maxlength="64" placeholder="example@email.com" required>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <input id="id_adults" name="adults" class="form-control form-control-sm" type="number" min="0" max="10" placeholder="Adults">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <input id="id_kids" name="kids" class="form-control form-control-sm" type="number" min="0" max="10" placeholder="Kids">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-check-inline">
                            <label class="form-check-label" style="font-size: 12pt;">
                                Do you have any pet?<input id="id_pets" name="pets" type="checkbox" class="form-check-input" style="height: 15px; width: 15px; margin-top: 5px; margin-left: 20px;">
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <input id="id_username" name="username" class="form-control form-control-sm" type="text" maxlength="150" autofocus="" placeholder="Username" required>
                    <div class="alert alert-warning" role="alert" style="margin-top: 5px;">
                        Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
                    </div>
                </div>
                <div class="form-group">
                    <input id="id_password1" name="password1" class="form-control form-control-sm" type="password" placeholder="Password" required>
                    <div class="alert alert-warning" role="alert" style="margin-top: 5px;">
                        <li>Your password can't be too similar to your other personal information.</li>
                        <li>Your password must contain at least 8 characters.</li>
                        <li>Your password can't be a commonly used password.</li>
                        <li>Your password can't be entirely numeric.</li>
                    </div>
                </div>
                <div class="form-group">
                    <input id="id_password2" name="password2" class="form-control form-control-sm" type="password" placeholder="Password confirmation" required>
                    <div class="alert alert-warning" role="alert" style="margin-top: 5px;">
                        Enter the same password as before, for verification.
                    </div>
                </div>
                <!-- **** Manage any error inside the form **** -->
                {% if form.errors %}
                    {% for field in form %}
                        {% if field.errors %}
                        <div class="form-error alert alert-danger" style="font-size: 11px;" role="alert">
                            {% for err in field.errors %}
                                <li>{{ err }}</li>
                            {% endfor %}
                        </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <button type="submit" class="btn-sm btn-signup">Create an account</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}